### PR TITLE
Check if git tag matches Cargo version when releasing

### PR DESCRIPTION
**Pull request by ribbanya**
[Test run](https://github.com/ribbanya/decomp-toolkit/actions/runs/8090525414/job/22108145400#step:3:51).

### CODE REVIEW

**Comment by ribbanya** [comment]
Oh, this fails on Windows. Umm... I'll fix it soon.

**Comment by ribbanya** [comment]
[Works now](https://github.com/ribbanya/decomp-toolkit/actions/runs/8090687084/job/22108555520).

**Comment by ribbanya** [comment]
[Passing version](https://github.com/ribbanya/decomp-toolkit/actions/runs/8090714526/job/22108631084#step:3:1).

**Comment by encounter** [comment]
Thanks a lot!

**Pull request merged**
